# Generated by Django 5.1.8 on 2025-04-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_in_service',
            field=models.BooleanField(default=True),
        ),
    ]
